"""Add biometric_id to logs

Revision ID: 236db65c3149
Revises: 36cac4b2e725
Create Date: 2025-08-13 11:51:56.258411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236db65c3149'
down_revision = '36cac4b2e725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biometric_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_column('biometric_id')

    # ### end Alembic commands ###
