"""Ajout colonne biometric_id dans employees

Revision ID: 36cac4b2e725
Revises: 2fa733ca52d8
Create Date: 2025-08-12 19:17:14.940612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36cac4b2e725'
down_revision = '2fa733ca52d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biometric_id', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['biometric_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('biometric_id')

    # ### end Alembic commands ###
